package ehsan.haghdoust.kanban.model

import com.google.gson.annotations.SerializedName

data class Task(@SerializedName(value = "id") var id: Int? = null,
                @SerializedName(value = "name") var name: String? = null,
                @SerializedName(value = "sequence") var sequence: Int? = null,
                @SerializedName(value = "priority") var priority: String? = null,
                @SerializedName(value = "status") var status: Int? = null,
                @SerializedName(value = "repeat") var repeat: String? = null,
                @SerializedName(value = "notes") var notes: String? = null,
                @SerializedName(value = "flagged") var flagged: String? = null,
                @SerializedName(value = "assigned_to_id") var assignedToId: String? = null,
                @SerializedName(value = "tracked_time") var trackedTime: Int? = null,
                @SerializedName(value = "created_by_id") var createdById: Int? = null,
                @SerializedName(value = "created_by_origin") var createdByOrigin: String? = null,
                @SerializedName(value = "reminder") var reminder: String? = null,
                @SerializedName(value = "created_at") var createdAt: String? = null,
                @SerializedName(value = "updated_at") var updatedAt: String? = null,
                @SerializedName(value = "section_id") var sectionId: Int? = null,
                @SerializedName(value = "token") var token: String? = null,
                @SerializedName(value = "comments_count") var commentsCount: Int? = null,
                @SerializedName(value = "status_changed_by_id") var statusChangedById: Int? = null,
                @SerializedName(value = "due") var due: String? = null,
                @SerializedName(value = "attachments_count") var attachmentsCount: Int? = null,
                @SerializedName(value = "closed_cl_items_count") var closedClItemsCount: Int? = null,
                @SerializedName(value = "total_cl_items_count") var totalClItemsCount: Int? = null,
                @SerializedName(value = "status_updated_at") var statusUpdatedAt: String? = null,
                @SerializedName(value = "meta_information") var metaInformation: String? = null,
                @SerializedName(value = "attachment_id") var attachmentId: String? = null,
                @SerializedName(value = "completed_at") var completedAt: String? = null)
